version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:12.19.0
      - image: maateen/docker-beanstalkd:1.11-alpine-latest
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  test:
    jobs:
      - test
  
