version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:12.19.0
      - image: cahva/docker-beanstalkd:v1
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  test:
    jobs:
      - test
  
